Console.Clear();
Console.WriteLine("Введите 1-е число ");
int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите 2-е число ");
int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите 3-е число ");
int c = Convert.ToInt32(Console.ReadLine());
int max = 0;
if ( a > max ) max = a;
if ( b > max ) max = b;
if ( c > max ) max = c;
Console.Write("max = ");
Console.WriteLine(max);